### ISSUE TITLE
OW bug: Softlock when entering a map

### ISSUE THREAD

**Issue by WD200019** [RhenaudTheLukark/CreateYourFrisk#20] opened 2018-07-08 16:12 UTC
**Description**
In CYF's Overworld, if you walk South of the starting screen, the game will go to a black screen and the music will keep playing, but nothing will happen.

**To Reproduce**
1. Enter CYF's Overworld in-game as any character
2. Walk off the bottom side of the screen

**Expected behavior**
The game should transition the player to the inside of the CORE, at the bridge with Punderbolt.

**Setup (please complete the following information):**
 - OS: Windows
 - Version 0.6.1.2

**Comment by RhenaudTheLukark** [comment] 2018-07-08 16:13
It looks weird, I'll check this out.

**Comment by RhenaudTheLukark** [comment] 2018-07-09 10:29
I can't reproduce this bug using the Windows x64 version of 0.6.1.2. Would you mind sending me your log file? 
In order to find it, you'll need to go on the Overworld and press the T key in order to show the path to the log file.
Some folders may be hidden, in this case type the exact path CYF is gining you and you'll be able to reach it.

**Comment by WD200019** [comment] 2018-07-09 14:03
Of course, here! [output_log.txt](https://github.com/RhenaudTheLukark/CreateYourFrisk/files/2176468/output_log.txt)

Line 98 is the last line that appeared before I actually took the screen transition. After that, the rest of the lines only appeared once I closed CYF.

**Comment by RhenaudTheLukark** [comment] 2018-07-09 17:00
Looking at the error, it seems you're missing the mod "OverWorld Test", as the folder "Mods/OverWorld Test/Sprites" can't be found.
Can you check if you have this mod? It should be one of CYF's basic mods, one that should never be deleted.

**Comment by WD200019** [comment] 2018-07-09 17:07
Oh, indeed it is missing, you are right. Terribly sorry, I did a goof...downloading CYF again and putting the mod back fixed it.

I forgot that I did that... >.>

**Comment by RhenaudTheLukark** [comment] 2018-07-09 17:09
It's alright, but maybe it's a good thing if I could add an error instead of leaving the game in such a state...
I will try to do that tomorrow, I'll tell you more on that when it'll be done.

**Comment by RhenaudTheLukark** [comment] 2018-07-15 00:14
I committed this new screen I was talking about some days ago, now there should not be any problem if a mod's missing in the overworld.

**Closed by RhenaudTheLukark** 2018-07-15 00:14 UTC
Labels: invalid
